[workspace]
members = ["crates/*"]
resolver = "2"

[workspace.package]
version = "0.0.1"
authors = ["fankai Liu <liufankai137@outlook.com>"]
edition = "2021"
description = """
tofo
"""
license = "MIT OR Apache-2.0"

[workspace.dependencies]
